import{a as b,S as L,i as n}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&s(f)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const w="44258731-7daca7e4db35e40c882241eb9",S="https://pixabay.com/api/";async function m(e,r=1,a=15){const s=`${S}?key=${w}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${a}`,t=await b.get(s);if(t.status!==200)throw new Error("Failed to fetch images");return t.data}let c=null;function h(e){const r=document.querySelector(".gallery"),a=e.map(s=>v(s)).join("");r.insertAdjacentHTML("beforeend",a),c&&c.destroy(),c=new L(".gallery a"),c.refresh()}function v(e){return`
    <a href="${e.largeImageURL}" class="gallery__item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="info-item"><b>Views:</b> ${e.views}</p>
        <p class="info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `}function $(){document.querySelector(".gallery").innerHTML=""}let l="",i=1;const d=15,u=document.querySelector(".load-more"),y=document.querySelector(".loader");document.querySelector("#search-form").addEventListener("submit",E);u.addEventListener("click",q);async function E(e){if(e.preventDefault(),l=e.currentTarget.elements.searchQuery.value.trim(),l===""){n.error({title:"Error",message:"Search field cannot be empty!"});return}i=1,$(),u.classList.add("hidden"),g();try{const r=await m(l,i,d);if(r.hits.length===0){n.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}h(r.hits),r.totalHits>d&&u.classList.remove("hidden")}catch{n.error({title:"Error",message:"Failed to fetch images"})}finally{p()}}async function q(){i+=1,g();try{const e=await m(l,i,d);h(e.hits);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i*d>=e.totalHits&&(n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),u.classList.add("hidden"))}catch{n.error({title:"Error",message:"Failed to fetch images"})}finally{p()}}function g(){y.classList.remove("hidden")}function p(){y.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
