(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const p="44258731-7daca7e4db35e40c882241eb9",b="https://pixabay.com/api/";async function f(e,r=1,i=15){const s=`${b}?key=${p}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${i}`,t=await axios.get(s);if(t.status!==200)throw new Error("Failed to fetch images");return t.data}let n=null;function m(e){const r=document.querySelector(".gallery"),i=e.map(s=>L(s)).join("");r.insertAdjacentHTML("beforeend",i),n&&n.destroy(),n=new SimpleLightbox(".gallery a"),n.refresh()}function L(e){return`
    <a href="${e.largeImageURL}" class="gallery__item">
      <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="info-item"><b>Views:</b> ${e.views}</p>
        <p class="info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </a>
  `}function w(){document.querySelector(".gallery").innerHTML=""}let c="",a=1;const l=15,d=document.querySelector(".load-more"),h=document.querySelector(".loader");document.querySelector("#search-form").addEventListener("submit",v);d.addEventListener("click",S);async function v(e){if(e.preventDefault(),c=e.currentTarget.elements.searchQuery.value.trim(),c===""){iziToast.error({title:"Error",message:"Search field cannot be empty!"});return}a=1,w(),d.classList.add("hidden"),y();try{const r=await f(c,a,l);if(r.hits.length===0){iziToast.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}m(r.hits),r.totalHits>l&&d.classList.remove("hidden")}catch{iziToast.error({title:"Error",message:"Failed to fetch images"})}finally{g()}}async function S(){a+=1,y();try{const e=await f(c,a,l);m(e.hits);const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),a*l>=e.totalHits&&(iziToast.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),d.classList.add("hidden"))}catch{iziToast.error({title:"Error",message:"Failed to fetch images"})}finally{g()}}function y(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
